///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package AXI_TEST_axi_vip_1_0_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter AXI_TEST_axi_vip_1_0_VIP_PROTOCOL           = 0;
      parameter AXI_TEST_axi_vip_1_0_VIP_READ_WRITE_MODE    = "READ_ONLY";
      parameter AXI_TEST_axi_vip_1_0_VIP_INTERFACE_MODE     = 2;
      parameter AXI_TEST_axi_vip_1_0_VIP_ADDR_WIDTH         = 32;
      parameter AXI_TEST_axi_vip_1_0_VIP_DATA_WIDTH         = 32;
      parameter AXI_TEST_axi_vip_1_0_VIP_ID_WIDTH           = 1;
      parameter AXI_TEST_axi_vip_1_0_VIP_AWUSER_WIDTH       = 0;
      parameter AXI_TEST_axi_vip_1_0_VIP_ARUSER_WIDTH       = 1;
      parameter AXI_TEST_axi_vip_1_0_VIP_RUSER_WIDTH        = 1;
      parameter AXI_TEST_axi_vip_1_0_VIP_WUSER_WIDTH        = 0;
      parameter AXI_TEST_axi_vip_1_0_VIP_BUSER_WIDTH        = 0;
      parameter AXI_TEST_axi_vip_1_0_VIP_SUPPORTS_NARROW    = 0;
      parameter AXI_TEST_axi_vip_1_0_VIP_HAS_BURST          = 1;
      parameter AXI_TEST_axi_vip_1_0_VIP_HAS_LOCK           = 0;
      parameter AXI_TEST_axi_vip_1_0_VIP_HAS_CACHE          = 1;
      parameter AXI_TEST_axi_vip_1_0_VIP_HAS_REGION         = 0;
      parameter AXI_TEST_axi_vip_1_0_VIP_HAS_QOS            = 1;
      parameter AXI_TEST_axi_vip_1_0_VIP_HAS_PROT           = 1;
      parameter AXI_TEST_axi_vip_1_0_VIP_HAS_WSTRB          = 0;
      parameter AXI_TEST_axi_vip_1_0_VIP_HAS_BRESP          = 0;
      parameter AXI_TEST_axi_vip_1_0_VIP_HAS_RRESP          = 1;
      parameter AXI_TEST_axi_vip_1_0_VIP_HAS_ACLKEN         = 0;
      parameter AXI_TEST_axi_vip_1_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi_slv_agent #(AXI_TEST_axi_vip_1_0_VIP_PROTOCOL, 
                        AXI_TEST_axi_vip_1_0_VIP_ADDR_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_DATA_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_DATA_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_ID_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_ID_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_AWUSER_WIDTH, 
                        AXI_TEST_axi_vip_1_0_VIP_WUSER_WIDTH, 
                        AXI_TEST_axi_vip_1_0_VIP_BUSER_WIDTH, 
                        AXI_TEST_axi_vip_1_0_VIP_ARUSER_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_RUSER_WIDTH, 
                        AXI_TEST_axi_vip_1_0_VIP_SUPPORTS_NARROW, 
                        AXI_TEST_axi_vip_1_0_VIP_HAS_BURST,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_LOCK,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_CACHE,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_REGION,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_PROT,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_QOS,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_WSTRB,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_BRESP,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_RRESP,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_ARESETN) AXI_TEST_axi_vip_1_0_slv_t;

typedef axi_slv_mem_agent #(AXI_TEST_axi_vip_1_0_VIP_PROTOCOL, 
                        AXI_TEST_axi_vip_1_0_VIP_ADDR_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_DATA_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_DATA_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_ID_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_ID_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_AWUSER_WIDTH, 
                        AXI_TEST_axi_vip_1_0_VIP_WUSER_WIDTH, 
                        AXI_TEST_axi_vip_1_0_VIP_BUSER_WIDTH, 
                        AXI_TEST_axi_vip_1_0_VIP_ARUSER_WIDTH,
                        AXI_TEST_axi_vip_1_0_VIP_RUSER_WIDTH, 
                        AXI_TEST_axi_vip_1_0_VIP_SUPPORTS_NARROW, 
                        AXI_TEST_axi_vip_1_0_VIP_HAS_BURST,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_LOCK,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_CACHE,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_REGION,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_PROT,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_QOS,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_WSTRB,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_BRESP,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_RRESP,
                        AXI_TEST_axi_vip_1_0_VIP_HAS_ARESETN) AXI_TEST_axi_vip_1_0_slv_mem_t;
                        
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      AXI_TEST_axi_vip_1_0_slv_t  AXI_TEST_axi_vip_1_0_slv;
//      initial begin : START_AXI_TEST_axi_vip_1_0_SLAVE
//        AXI_TEST_axi_vip_1_0_slv = new("AXI_TEST_axi_vip_1_0_slv", `AXI_TEST_axi_vip_1_0_PATH_TO_INTERFACE);
//        AXI_TEST_axi_vip_1_0_slv.start_slave();
//      end

endpackage : AXI_TEST_axi_vip_1_0_pkg
