#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Sep 12 09:27:42 CEST 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim AXI_TEST_wrapper_tb_behav -key {Behavioral:sim_1:Functional:AXI_TEST_wrapper_tb} -tclbatch AXI_TEST_wrapper_tb.tcl -protoinst "protoinst_files/bd_e000.protoinst" -protoinst "protoinst_files/re2_bd.protoinst" -protoinst "protoinst_files/AXI_TEST.protoinst" -log simulate.log"
xsim AXI_TEST_wrapper_tb_behav -key {Behavioral:sim_1:Functional:AXI_TEST_wrapper_tb} -tclbatch AXI_TEST_wrapper_tb.tcl -protoinst "protoinst_files/bd_e000.protoinst" -protoinst "protoinst_files/re2_bd.protoinst" -protoinst "protoinst_files/AXI_TEST.protoinst" -log simulate.log

